export enum ErrorCode {
  // Auth
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_EMAIL_NOT_VERIFIED = 'AUTH_EMAIL_NOT_VERIFIED',

  // Profile
  PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND',

  // Session
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  SESSION_INVALID_STATUS = 'SESSION_INVALID_STATUS',
  SESSION_TIMER_EXPIRED = 'SESSION_TIMER_EXPIRED',
  SESSION_ALREADY_ANSWERED = 'SESSION_ALREADY_ANSWERED',

  // Package
  PACKAGE_UNAVAILABLE = 'PACKAGE_UNAVAILABLE',

  // Result
  RESULT_NOT_READY = 'RESULT_NOT_READY',

  // Validation
  VALIDATION_ERROR = 'VALIDATION_ERROR',
}
